In [2]:
import numpy as np

In [3]:
np.__version__

'2.1.2'

# Creating Array using list

In [5]:
a = [1,2,3,4]  #list

In [6]:
np.array(a)

array([1, 2, 3, 4])

In [7]:
arr1 = np.array(a)

In [8]:
type(arr1)

numpy.ndarray

In [11]:
b = [True, False, False, True, True, False]
print(type(b))

arr2 = np.array(b)
print(type(arr2))
print(arr2)

<class 'list'>
<class 'numpy.ndarray'>
[ True False False  True  True False]


In [12]:
c = [True, 0, 9.8, True, -10, False]
print(type(c))

arr3 = np.array(c)
print(type(arr3))
print(arr3)

<class 'list'>
<class 'numpy.ndarray'>
[  1.    0.    9.8   1.  -10.    0. ]


In [14]:
float(False)

0.0

# Creating array without using list

In [18]:
a = np.zeros(5)
print(a)
print(type(a))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones(shape=5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [35]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(1)

array([[1.]])

In [38]:
a = [1,2,3,4,5]

In [42]:
[i+2 for i in a]

[3, 4, 5, 6, 7]

In [46]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [47]:
a + 2

array([3, 4, 5, 6, 7])

In [48]:
a - 10

array([-9, -8, -7, -6, -5])

In [49]:
a / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

# Creating array- using arange function

In [50]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [51]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [58]:
a = np.arange(31,40)
a

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [62]:
print(a[0])

31


In [64]:
print(a[8])

39


# Reshaping array

In [68]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
b = np.arange(50,65).reshape(3,5)
print(b)

[[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]]


In [75]:
b.shape

(3, 5)

In [ ]:
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


# Array slicing

In [83]:
a = np.arange(0,20).reshape(4,5)
print(a)
print(a.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [84]:
a[0,:]

array([0, 1, 2, 3, 4])

In [87]:
a[0,2]

np.int64(2)

In [86]:
print(a[0,2])

2


In [89]:
a[1,3:]

array([8, 9])

In [91]:
a[1,3:5]

array([8, 9])

In [92]:
a.shape

(4, 5)

In [93]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
a[3,:]

array([15, 16, 17, 18, 19])

In [95]:
a[3,1:4]

array([16, 17, 18])

In [98]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [101]:
t = list(range(10))
t

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [102]:
t[2:5]

[2, 3, 4]

In [103]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [108]:
a[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [109]:
# Assignment
# Get 0, 1, 5, 6 from this above array

In [ ]:
# Assignment
# Get 12,13,14 and 17,18,19 from this above array

## Link to Python Data Science Handbook
Fork this repo and then clone to your local 
- https://github.com/jakevdp/PythonDataScienceHandbook